src/Entity/Immobilier.php
<?php

namespace App\Entity;

use App\Repository\ImmobilierRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImmobilierRepository::class)]
class Immobilier
{
    #[ORM\Id]
    #[ORM\Column]
    private ?int $id_fiscal = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?int $superficie = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'immobiliers')]
    private ?Utilisateur $id_user = null;

    #[ORM\Column(length: 255)]
    private ?string $titre_prop = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Evaluation $evaluation = null;

    public function getIdfiscal(): ?int
    {
        return $this->id_fiscal;
    }

    public function setIdfiscal(string $id_fiscal): static
    {
        $this->id_fiscal = $id_fiscal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getSuperficie(): ?int
    {
        return $this->superficie;
    }

    public function setSuperficie(int $superficie): static
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getIdUser(): ?Utilisateur
    {
        return $this->id_user;
    }

    public function setIdUser(?Utilisateur $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getTitreProp(): ?string
    {
        return $this->titre_prop;
    }

    public function setTitreProp(string $titre_prop): static
    {
        $this->titre_prop = $titre_prop;

        return $this;
    }

    public function getEvaluation(): ?Evaluation
    {
        return $this->evaluation;
    }

    public function setEvaluation(?Evaluation $evaluation): static
    {
        $this->evaluation = $evaluation;

        return $this;
    }
}

src/Form/expertise/ImmobilierType.php
<?php

namespace App\Form;

use App\Entity\Immobilier;
use App\Enum\typeImm;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints as Assert;

class ImmobilierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_fiscal',NumberType::class,[
                'constraints' => [
                    new Assert\NotBlank(message:"L'identifiant fiscale est obligatoire"),
                ],
            ])
            ->add('adresse',TextType::class,[
                'constraints' => [
                    new Assert\NotBlank(message:"L'adresse' est obligatoire"),
                ],
            ])
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Villa' => typeImm::V,
                    'Etage Villa' => typeImm::EV,
                    'Appartement' => typeImm::A,
                ],
                'constraints' => [
                    new Assert\NotBlank(message:'Le type est obligatoire'),
                ],
                'placeholder' => "Sélectionnez le type de l'immobilier",
            ])
            ->add('superficie',NumberType::class,[
                'constraints' => [
                    new Assert\NotBlank(message:'La superficie est obligatoire'),
                ],
            ])
            ->add('titre_prop',FileType::class, [
                'label' => 'Image',
                'required' => true, // Set to true if the image is mandatory
                'mapped' => false, // This tells Symfony not to try to map this field to any entity property
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image file (JPEG, PNG)',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Immobilier::class,
        ]);
    }
}

src/Controller/ImmobilierController.php
<?php

namespace App\Controller;

use App\Entity\Immobilier;
use App\Entity\Utilisateur;
use App\Form\ImmobilierType;
use App\Repository\ImmobilierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/client/MyEstates')]
class ImmobilierController extends AbstractController
{
    #[Route('/', name: 'app_immobilier_index', methods: ['GET'])]
    public function index(Request $request,ImmobilierRepository $immobilierRepository): Response
    {
        $user_id = $request->getSession()->get('user_id');
        $sortBy = $request->query->get('sort_by'); // Récupérer le paramètre de tri
        $searchTerm = $request->query->get('q'); // Récupérer le terme de recherche
    
        // Si le paramètre de tri n'est pas défini, tri par défaut par ID
        if (!$sortBy || !in_array($sortBy, ['id_fiscal', 'superficie'])) {
            $sortBy = 'id_fiscal';
        }
    
        // Récupérer les données en fonction du tri souhaité et du terme de recherche
        $immobiliers = $immobilierRepository->findBySearchTerm($searchTerm, $sortBy);
    
        return $this->render('immobilier/index.html.twig', [
            'immobiliers' => $immobiliers,
            'user' => $user_id,
            'searchTerm' => $searchTerm, // Passer le terme de recherche au modèle Twig
        ]);
    }

    #[Route('/new', name: 'app_immobilier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $immobilier = new Immobilier();
        $form = $this->createForm(ImmobilierType::class, $immobilier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $immobilierId = $immobilier->getIdfiscal();
            $immobilierType = $immobilier->getType();
            $tempFilePath = $form['titre_prop']->getData();
            $nameph = $immobilierType.$immobilierId.".png";
            $destinationPath = "uploads/".$nameph;
            $compressionQuality = 100;
    
            $this->compressImage($tempFilePath, $destinationPath, $compressionQuality);
            
            $user_id = $request->getSession()->get('user_id');
            $user = $entityManager->getRepository(Utilisateur::class)->findOneBy(['id' => $user_id]);
            $immobilier->setIdUser($user);
            $immobilier->setTitreProp($nameph);
            $immobilier->setStatus("Non Validée");
            $entityManager->persist($immobilier);
            $entityManager->flush();

            return $this->redirectToRoute('app_immobilier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('immobilier/new.html.twig', [
            'immobilier' => $immobilier,
            'form' => $form,
        ]);
    }

    #[Route('/{id_fiscal}', name: 'app_immobilier_show', methods: ['GET'])]
    public function show(Immobilier $immobilier): Response
    {
        return $this->render('immobilier/show.html.twig', [
            'immobilier' => $immobilier,
        ]);
    }

    #[Route('/{id_fiscal}/edit', name: 'app_immobilier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Immobilier $immobilier, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ImmobilierType::class, $immobilier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_immobilier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('immobilier/edit.html.twig', [
            'immobilier' => $immobilier,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id_fiscal}', name: 'app_immobilier_delete', methods: ['GET','POST'])]
    public function delete(Request $request, Immobilier $immobilier, EntityManagerInterface $entityManager): Response
    {
            $immobilier->setIdUser(null);
            $entityManager->remove($immobilier);
            $entityManager->flush();

        return $this->redirectToRoute('app_immobilier_index', [], Response::HTTP_SEE_OTHER);
    }
    
    private  function compressImage($source, $destination, $quality) {
        $info = getimagesize($source);
        
        if ($info['mime'] == 'image/jpeg') {
            $image = imagecreatefromjpeg($source);
        } elseif ($info['mime'] == 'image/png') {
            $image = imagecreatefrompng($source);
        } elseif ($info['mime'] == 'image/gif') {
            $image = imagecreatefromgif($source);
        } else {
            return false;
        }    // Sauvegarder l'image compressée
        $filename = substr($destination, strpos($destination, '/') + 1);
        $destination2 = "C:/Users/hails/Pictures/Assurancy/Assurancy/src/main/resources/assets/uploads/".$filename;
        
        // Save the compressed image
        imagejpeg($image, $destination, $quality);
        imagejpeg($image, $destination2, $quality);
           
           // Libérer la mémoire
           imagedestroy($image);
           
           return true;
       }
        
        
}

templates/immobilier/_delete_form.html.twig
<form method="post" action="{{ path('app_immobilier_delete', {'id_fiscal': immobilier.id_fiscal}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ immobilier.id_fiscal) }}">
    <button class="btn">Delete</button>
</form>

templates/immobilier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/immobilier/edit.html.twig
{% extends 'base.html.twig' %}

{% block nav %}
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container"><img src="{{ asset('assets/img/icons/logoWM.png') }}" alt=""><a class="navbar-brand" href="{{ path('index') }}"><span class="text-primary fs-3 ms-2 fw-bolder">ss</span><span class="fw-thin text-300 fs-3">urancy.tn</span></a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse pt-4 pt-lg-0" id="navbarSupportedContent">
            <p class="mb-0 ms-auto text-light fs-0 fw-normal"><i class="fas fa-phone-alt me-2"></i>Appelez-nous  <a class="text-light" href="tel:+216 92440011">+216 92440011</a></p>
            <ul class="navbar-nav ms-auto border-bottom border-lg-bottom-0 pt-2 pt-lg-0">
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('index') }}">Accueil</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('offres') }}">Nos offres</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('ajouter_un_bien') }}">Ajouter un bien</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('services') }}">Services rapides</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('about') }}">À propos nous</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('assistance') }}">Assitance</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('community') }}">Communauté</a></li>
            </ul>
            <div class="d-flex mt-2 align-items-center mt-lg-0">
              <a href="{{ path('login') }}"> <i class="fas fa-user text-primary"> </i></a>
            </div>
          </div>
        </div>
      </nav>
{% endblock %}

{% block body %}
        <div class="bg-holder d-none d-md-block" style="background-image:url(assets/img/illustrations/bg-car-insurance.png);background-position:left top;background-size:100% 85%;"></div>
        <div class="container">
          <div class="row-cols-2 d-flex align-items-center justify-content-center">
            <div class="card card-bg shadow hero-header-form">
                <div class="card-body p-4 p-xl-6">
                    <h1 class="display-2 text-light fw-thin text-center">Editer un immobilier</h1>
    {{ form_start(form,{'attr': {'novalidate': 'novalidate'}}) }}

    <div class="form-floating mb-3">
        {{ form_widget(form.id_fiscal , {'attr': {'class': 'form-control input-box form-ensurance-header-control', 'placeholder': 'surname'}}) }}
        {{ form_label(form.id_fiscal , 'id fiscale') }}
    </div>

    <div class="form-floating mb-3">
        {{ form_widget(form.adresse, {'attr': {'class': 'form-control input-box form-ensurance-header-control', 'placeholder': 'name'}}) }}
        {{ form_label(form.adresse, 'adresse') }}
    </div>

    <div class="form-floating mb-3">
        {{ form_widget(form.type, {'attr': {'class': 'form-control input-box form-ensurance-header-control', 'placeholder': 'date'}}) }}
        {{ form_label(form.type, 'type') }}
    </div>

    <div class="form-floating mb-3">
        {{ form_widget(form.superficie, {'attr': {'class': 'form-control input-box form-ensurance-header-control', 'placeholder': 'address'}}) }}
        {{ form_label(form.superficie, 'Superficie') }}
    </div>

   

    <div class="form-floating mb-3">
        {{ form_widget(form.titre_prop, {'attr': {'class': 'form-control input-box form-ensurance-header-control', 'placeholder': 'tel'}}) }}
        {{ form_label(form.titre_prop, 'titre prop') }}
    </div>

   
    

    <div class="col-12 d-grid">
        <button class="btn btn-primary rounded-pill" type="submit">Enregistrer</button>
    </div>

    {{ form_end(form) }}

                </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/immobilier/index.html.twig
{% extends 'base.html.twig' %}

{% block nav %}
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container"><img src="{{ asset('assets/img/icons/logoWM.png') }}" alt=""><a class="navbar-brand" href="{{ path('index') }}"><span class="text-primary fs-3 ms-2 fw-bolder">ss</span><span class="fw-thin text-300 fs-3">urancy.tn</span></a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse pt-4 pt-lg-0" id="navbarSupportedContent">
            <p class="mb-0 ms-auto text-light fs-0 fw-normal"><i class="fas fa-phone-alt me-2"></i>Call us<a class="text-light" href="tel:+216 92440011">+216 92440011</a></p>
            <ul class="navbar-nav ms-auto border-bottom border-lg-bottom-0 pt-2 pt-lg-0">
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('index') }}">Home</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('offres') }}">Our offers</a></li>
              <li class="nav-item px-2"><a class="nav-link active" aria-current="page" href="{{ path('ajouter_un_bien') }}">My goods</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('services') }}">Fast services</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('about') }}">About us</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('assistance') }}">Assitance</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('community') }}">Community</a></li>
              {% if (app.session.get('user_role') != "Client") %}
              <li class="nav-item px-0"><a class="nav-link" href="{{ path('app_dashboard') }}">Dashboard</a></li>
              {% endif %}
            </ul>
            <div class="d-flex mt-2 align-items-center mt-lg-0">
              <div class="dropdown">
                <button class="btn btn-sm d-flex mx-2" id="dropdownMenuButton1" type="submit" data-bs-toggle="dropdown" aria-expanded="false"><img style="border-radius: 50%; width: 30px; height: 30px;" src="{{ asset('uploads/' ~ app.session.get('user_image')|default('images/faces/face28.jpg')) }}" alt="profile"/></button>
                <div class="dropdown-menu dropdown-menu-dark dropdown-menu-lg-end p-0 rounded" aria-labelledby="dropdownMenuButton1" style="top:55px">
                  <p class="mb-0 ms-auto text-light fs-0 fw-normal text-center">{{app.session.get('user_name')}}</p>
                  <a class="dropdown-item" href="{{ path('profile',{'id': app.session.get('user_id')}) }}"><i class="fas fa-user-edit text-primary" style="color: black;"></i>   My profile</a>
                  <a class="dropdown-item" href="{{ path('logout') }}"><i class="fas fa-sign-out-alt text-danger"></i>    Logout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
{% endblock %}

{% block body %}
        <div class="bg-holder d-none d-md-block" style="background-image:url(assets/img/illustrations/bg-car-insurance.png);background-position:left top;background-size:100% 85%;"></div>
        <div class="container">
          <div class="row-cols-2 d-flex align-items-center justify-content-center">
            <div class="card card-bg shadow hero-header-form">
                <div class="card-body p-4 p-xl-6">
                <a class="btn btn-primary my-1" href="{{ path('ajouter_un_bien') }}">Back</a>
                    <h1 class="display-2 text-light fw-thin text-center">Mes immobiliers</h1>
                    <div class="d-flex align-items-center"> <!-- Conteneur flexbox pour aligner les éléments -->
    <div class="form-check form-check-inline me-3"> <!-- Première checkbox -->
        <input class="form-check-input" type="checkbox" id="tri_par_superficie" value="superficie" {% if app.request.query.get('sort_by') == 'superficie' %}checked{% endif %} onchange="triimmobilier(this)">
        <label class="form-check-label" for="tri_par_superficie">Trier par superficie</label>
    </div>
    <div class="form-check form-check-inline me-3"> <!-- Deuxième checkbox -->
        <input class="form-check-input" type="checkbox" id="tri_par_id_fiscal" value="id_fiscal" {% if app.request.query.get('sort_by') == 'id_fiscal' %}checked{% endif %} onchange="triimmobilier(this)">
        <label class="form-check-label" for="tri_par_id_fiscal">Trier par Id fiscal</label>
    </div>
    <form action="{{ path('app_immobilier_index') }}" method="GET" class="d-flex"> <!-- Barre de recherche -->
        <input type="text" name="q" value="{{ searchTerm }}" placeholder="Rechercher..." class="form-control me-2">
        <button type="submit" class="btn btn-primary">Rechercher</button>
    </form>
</div>

                
    <table style="width=80%;">
        <thead>
            <tr>
                <th>Id_fiscal</th>
                <th>Adresse</th>
                <th>Type</th>
                <th>Superficie</th>
                <th>Titre_prop</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for immobilier in immobiliers %}
            {% if immobilier.idUser.id == user %}
            <tr>
                <td>{{ immobilier.idFiscal }}</td>
                <td>{{ immobilier.adresse }}</td>
                <td>{{ immobilier.type }}</td>
                <td>{{ immobilier.superficie }}</td>
                <td><a href="{{ asset(immobilier.titreProp) }}" target="_blank"><img src="{{ asset('uploads/' ~ immobilier.titreProp) }}" alt="" style="width: 50px; height: 50px;"></a></td>
                <td>{{ immobilier.status }}</td>
                <td>
                    <a href="{{ path('app_immobilier_edit', {'id_fiscal': immobilier.idFiscal}) }}"><i class="fas fa-pencil-alt"></i></a>
                    <a href="{{ path('app_immobilier_delete', {'id_fiscal': immobilier.idFiscal}) }}"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_immobilier_new') }}">Create new</a>

        

                </div>
            </div>
          </div>
        </div>
        <script>
    function triimmobilier(checkbox) {
        const checkboxes = document.querySelectorAll('input[type="checkbox"]');
        checkboxes.forEach((box) => {
            if (box !== checkbox) {
                box.checked = false;
            }
        });

        const sortBy = checkbox.value;
        const currentUrl = new URL(window.location.href);
        currentUrl.searchParams.set('sort_by', sortBy);
        window.location.href = currentUrl.toString();
    }
</script>
{% endblock %}

templates/immobilier/show.html.twig
{% extends 'base.html.twig' %}

{% block nav %}
      <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" data-navbar-on-scroll="data-navbar-on-scroll">
        <div class="container"><img src="{{ asset('assets/img/icons/logoWM.png') }}" alt=""><a class="navbar-brand" href="{{ path('index') }}"><span class="text-primary fs-3 ms-2 fw-bolder">ss</span><span class="fw-thin text-300 fs-3">urancy.tn</span></a>
          <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse pt-4 pt-lg-0" id="navbarSupportedContent">
            <p class="mb-0 ms-auto text-light fs-0 fw-normal"><i class="fas fa-phone-alt me-2"></i>Appelez-nous  <a class="text-light" href="tel:+216 92440011">+216 92440011</a></p>
            <ul class="navbar-nav ms-auto border-bottom border-lg-bottom-0 pt-2 pt-lg-0">
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('index') }}">Accueil</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('offres') }}">Nos offres</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('ajouter_un_bien') }}">Ajouter un bien</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('services') }}">Services rapides</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('about') }}">À propos nous</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('assistance') }}">Assitance</a></li>
              <li class="nav-item px-2"><a class="nav-link" href="{{ path('community') }}">Communauté</a></li>
            </ul>
            <div class="d-flex mt-2 align-items-center mt-lg-0">
              <a href="{{ path('login') }}"> <i class="fas fa-user text-primary"> </i></a>
            </div>
          </div>
        </div>
      </nav>
{% endblock %}

{% block body %}
        <div class="bg-holder d-none d-md-block" style="background-image:url(assets/img/illustrations/bg-car-insurance.png);background-position:left top;background-size:100% 85%;"></div>
        <div class="container">
          <div class="row-cols-2 d-flex align-items-center justify-content-center">
            <div class="card card-bg shadow hero-header-form">
                <div class="card-body p-3 p-xl-6">
                    <h1 class="display-2 text-light fw-thin text-center">Mes immobiliers</h1>
    <table style="width=70%;">
        <tbody>
            <tr>
                <th>Id_fiscal</th>
                <td>{{ immobilier.idFiscal }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ immobilier.adresse }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ immobilier.type }}</td>
            </tr>
            <tr>
                <th>Superficie</th>
                <td>{{ immobilier.superficie }}</td>
            </tr>
            <tr>
                <th>Titre_prop</th>
                <td>{{ immobilier.titreProp }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ immobilier.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_immobilier_index') }}">back to list</a>

    <a href="{{ path('app_immobilier_edit', {'id_fiscal': immobilier.id_fiscal}) }}">edit</a>

    {{ include('immobilier/_delete_form.html.twig') }}

                </div>
            </div>
          </div>
        </div>
{% endblock %}